In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of juice',
      'the glass of milk',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'understand the meaning of words',
      'your vedios are good'
      ]

In [3]:
sent

['the glass of juice',
 'the glass of milk',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your vedios are good']

In [6]:
voc_size=10000

In [7]:
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[2857, 2175, 528, 7309],
 [2857, 2175, 528, 7304],
 [2857, 7709, 528, 5325],
 [620, 1329, 5811, 1201, 5393],
 [620, 1329, 5811, 1201, 7467],
 [8911, 2857, 8099, 528, 5987],
 [1664, 5144, 8382, 1201]]

In [11]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2857 2175  528 7309]
 [   0    0    0    0 2857 2175  528 7304]
 [   0    0    0    0 2857 7709  528 5325]
 [   0    0    0  620 1329 5811 1201 5393]
 [   0    0    0  620 1329 5811 1201 7467]
 [   0    0    0 8911 2857 8099  528 5987]
 [   0    0    0    0 1664 5144 8382 1201]]


In [14]:
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\mgane\OneDrive\Documents\ann\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 656ms/step


array([[[-1.42702088e-02,  4.23979647e-02, -3.74770872e-02,
         -2.86392216e-02,  9.95820761e-03, -3.86897214e-02,
          4.90323454e-03, -3.60145792e-02, -4.23123240e-02,
         -1.28539577e-02],
        [-1.42702088e-02,  4.23979647e-02, -3.74770872e-02,
         -2.86392216e-02,  9.95820761e-03, -3.86897214e-02,
          4.90323454e-03, -3.60145792e-02, -4.23123240e-02,
         -1.28539577e-02],
        [-1.42702088e-02,  4.23979647e-02, -3.74770872e-02,
         -2.86392216e-02,  9.95820761e-03, -3.86897214e-02,
          4.90323454e-03, -3.60145792e-02, -4.23123240e-02,
         -1.28539577e-02],
        [-1.42702088e-02,  4.23979647e-02, -3.74770872e-02,
         -2.86392216e-02,  9.95820761e-03, -3.86897214e-02,
          4.90323454e-03, -3.60145792e-02, -4.23123240e-02,
         -1.28539577e-02],
        [-4.21335548e-03, -1.15759373e-02, -3.63554731e-02,
          2.15945393e-03,  3.39359753e-02,  4.22109626e-02,
          3.05612572e-02,  1.56499036e-02, -4.448951